server:
  port: 5000

spring:
  task:
    scheduling:
      pool:
        size: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DeviceManagement
    password: 1234
    username: root

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/actuator

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: site.aoba.devicemanagement2api.infrastructure.mappers
  check-config-location: true

site:
  aoba:
    authorization:
      jwt:
        key: "773C542543664C65B30E713CFD5845E6"
        issuer: site.aoba.devicemanagement2api
      password:
        salt: "773C542543664C65B30E713CFD5845E6"